#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2012, Onur Küçük <onur at delipenguen.net>
#

f = file("words")
data = f.read()
f.close()

data = data.split()
for x in data:
    hede = sum(map(lambda z: int(x[z]) and 2**(len(x) - z - 1), range(len(x)-1, -1, -1)))
    print chr(hede),

