#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

tra = {'içerle': 'import',
        'yazdır': 'print',
        'döndür': 'for',
        'yi': 'in',
        'içinde': '',
        'dene': 'try',
        'olmadı': 'except'}

if not len(sys.argv) > 1:
  print 'Kullanım $ ./piton dosyaadi.pi'
  sys.exit()

kod = open(sys.argv[1], 'r').read()

for tt in tra.keys():
  kod = kod.replace(tt, tra[tt])

exec(kod)


