#!/bin/bash
#
# Copyright (C) 2012, Onur Küçük <onur at delipenguen.net>
#

SUM=0
OVERALL=0
VERBOSE=0

if [ "x$1" == "x-v" ]
then
    VERBOSE=1
fi

for DIR in `find /proc/ -maxdepth 1 -type d | egrep "^/proc/[0-9]"`
do
  PID=`echo $DIR | cut -d / -f 3`
  PROGNAME=`ps -p $PID -o comm --no-headers`

  for SWAP in `grep Swap $DIR/smaps 2>/dev/null| awk '{ print $2 }'`
  do
    let SUM=$SUM+$SWAP
  done

  if [ "x$SUM" != "x0" -o "x$VERBOSE" == "x1" ]
  then
    echo "PID=$PID - Swap used: $SUM - ($PROGNAME )"
  fi

  let OVERALL=$OVERALL+$SUM

  SUM=0
done

echo "Overall swap used: $OVERALL"


